# Generated by Django 4.2.7 on 2026-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_add_fields_to_community_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategory',
            name='icon',
            field=models.CharField(help_text='Nombre del icono de React Icons (ej: FaHeart, FaStar, FaUser). Consulta https://react-icons.github.io/react-icons/ para encontrar el icono correcto.', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='description',
            field=models.TextField(help_text='Contenido completo con formato enriquecido. Presiona Enter para nuevo párrafo, Shift+Enter para salto de línea.', verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='nuestrahistoria',
            name='paragraphs',
            field=models.TextField(help_text='Contenido completo con formato enriquecido. Presiona Enter para nuevo párrafo, Shift+Enter para salto de línea.', verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='paragraphs',
            field=models.TextField(help_text='Contenido completo con formato enriquecido. Presiona Enter para nuevo párrafo, Shift+Enter para salto de línea.', verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='description',
            field=models.TextField(help_text='Contenido completo con formato enriquecido. Presiona Enter para nuevo párrafo, Shift+Enter para salto de línea.', verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.TextField(help_text='Contenido completo con formato enriquecido. Presiona Enter para nuevo párrafo, Shift+Enter para salto de línea.', verbose_name='Contenido completo'),
        ),
    ]
