FROM nginx:alpine

# Copiar configuracion de produccion (sin upstream frontend-dev)
COPY default-prod.conf /etc/nginx/conf.d/default.conf

# Crear directorio para el frontend
RUN mkdir -p /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
