# Generated by Django 4.2.7 on 2026-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0011_province_suggestionbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la página de solicitudes de reclamaciones', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la página de solicitudes de reclamaciones', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la página está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Solicitudes de Reclamaciones',
                'verbose_name_plural': 'Páginas de Solicitudes de Reclamaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la página de reportes de fraude', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la página de reportes de fraude', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la página está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Reportes de Fraude',
                'verbose_name_plural': 'Páginas de Reportes de Fraude',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionBoxPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la página del buzón de sugerencias', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la página del buzón de sugerencias', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la página está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página del Buzón de Sugerencias',
                'verbose_name_plural': 'Páginas del Buzón de Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='yearlydocument',
            options={'ordering': ['-year', 'account_type', 'type'], 'verbose_name': 'Documento Anual', 'verbose_name_plural': 'Documentos Anuales'},
        ),
        migrations.AlterUniqueTogether(
            name='yearlydocument',
            unique_together=set(),
        ),
    ]
