# Generated by Django 4.2.7 on 2026-05-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0012_claimrequestpage_fraudreportpage_suggestionboxpage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearlydocument',
            unique_together=set(),
        ),
    ]
