# Generated by Django 4.2.7 on 2026-04-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_banner_image_to_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título principal del banner', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del banner', verbose_name='Descripción')),
                ('button1_name', models.CharField(help_text='Texto que aparecerá en el primer botón', max_length=100, verbose_name='Nombre del Botón 1')),
                ('button1_url', models.URLField(help_text='Enlace al que dirigirá el primer botón', verbose_name='URL del Botón 1')),
                ('button2_name', models.CharField(help_text='Texto que aparecerá en el segundo botón', max_length=100, verbose_name='Nombre del Botón 2')),
                ('button2_url', models.URLField(help_text='Enlace al que dirigirá el segundo botón', verbose_name='URL del Botón 2')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el banner está activo', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tipo de préstamo', max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador único para URLs (se genera automáticamente)', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de préstamo', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este tipo de préstamo está disponible', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='features',
            field=models.TextField(blank=True, help_text='Características del producto separadas por /', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='account',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos para abrir la cuenta separados por /', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='card',
            name='features',
            field=models.TextField(blank=True, help_text='Características de la tarjeta separadas por /', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='card',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos para obtener la tarjeta separados por /', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='investment_details',
            field=models.TextField(blank=True, help_text='Detalles de la inversión separados por /', verbose_name='Detalles de inversión'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos separados por /', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='details',
            field=models.TextField(default='', help_text='Detalles del préstamo separados por /', verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requirements',
            field=models.TextField(help_text='Requisitos del préstamo separados por /', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requirements_title',
            field=models.CharField(default='Requisitos para Crédito', help_text='Título de la sección de requisitos', max_length=200, verbose_name='Título de requisitos'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='title',
            field=models.CharField(help_text='Título del préstamo ', max_length=200, verbose_name='Título'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_banner'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(help_text='Selecciona el tipo de préstamo', on_delete=django.db.models.deletion.PROTECT, to='products.loantype', verbose_name='Tipo de préstamo'),
        ),
    ]
