# Generated by Django 4.2.7 on 2026-04-29 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_promotion_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo de imagen, video o documento', upload_to='news/', verbose_name='Archivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], default='image', help_text='Tipo de archivo', max_length=20, verbose_name='Tipo de media')),
                ('caption', models.CharField(blank=True, help_text='Descripción o pie de foto del archivo', max_length=200, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el archivo está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(help_text='Noticia a la que pertenece este archivo', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='news.news', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Archivo de Media',
                'verbose_name_plural': 'Archivos de Media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
