# Generated by Django 4.2.7 on 2026-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_change_steps_to_prose_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='steps',
            field=models.TextField(help_text='Pasos para usar el servicio (puedes usar listas con viñetas)', verbose_name='Pasos'),
        ),
    ]
